feat(invoice_detail_query_concern): add invoice detail id and bo invoice
5-stones/huginn_acumen_order_agent pull request #3
Opened 2021-03-05 16:09 UTC by Jhalter5Stones

add invoice detail id and back order invoice detail id

2021-03-05 16:11 UTC, Jhalter5Stones commented
@mrogers-5s Ready for review

https://trello.com/c/QMkQ8w69/451-asbat-get-shipment-updates-from-acumen

2021-03-05 16:51 UTC, Ken-Michalak approved these changes

2021-03-05 19:02 UTC, mrogers-5s requested changes
~~@Jhalter5Stones You'll also need to update the agent itself to actually _fetch_ the invoice details. Right now, this lookup isn't actually firing.~~

Disregard. I am blind.

2021-03-08 14:53 UTC, mrogers-5s approved these changes

2021-03-08 14:54 UTC, merged